[project]
name = "m3pyhunters"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.5",
    "django-debug-toolbar>=6.3.0",
    "django-extensions>=4.1",
    "django-filter>=26.1",
    "django-unfold>=0.99.0",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "dotenv>=0.9.9",
    "drf-spectacular>=0.30.0",
    "graphene-django>=3.2.3",
    "ipython>=9.14.1",
    "pillow>=12.3.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-django>=4.14.0",
]

[tool.pytest]
python_files = ["test_*.py", "*_test.py", 'tests.py']
DJANGO_SETTINGS_MODULE = "config.settings"
addopts = ["--cov", "--cov-report=html"]
