# Generated by Django 6.0.5 on 2026-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_post_delete_mymodel_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'В обработке'), ('published', 'Опубликовано')], default='draft'),
        ),
    ]
